githubRepoOwner: dmtrKovalenko
githubRepoName: odiff
githubHost: github.com
githubRemote: origin/chore
githubBranch: esy-nightly
requireChecks: true
requireApproval: true
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
showPrTitlesInStack: false
branchPushIndividually: false
